---
title: "Estadística II"
subtitle: "Introducción a la inferencia estadística"
author: "CruzJulián"

lang: "es-co"
---

```{r, echo = FALSE}

# Falta:
#   
#   Pasar todo esto al formato de openintrostatistics

"http://www.bnm.me.gov.ar/giga1/documentos/EL001858.pdf"


```

# Antecedentes

## Presentación

### Descripción del curso

Estadística 2: Estadística Inferencial para el seminario de Técnicas Especiales de Investigación II, es un curso muy rápido e introductorio que se ofrece a los estudiantes como parte del conjunto de herramientas que hacen parte de la programación completa de la materia. El contenido de las sesiones se plantea como introducción y con el objetivo de reforzar temas de estadística a los estudiantes sobre los conceptos de pruebas de estimación y pruebas de hipótesis.

### Justificación

Técnicas Especiales de Investigación II es la segunda de las cuatro materias del ciclo que orienta a los estudiantes en el desarrollo de sus proyectos de grado. Dado que la única estadística que se ofrece en los programas de Ciencias Sociales de Universidad Externado de Colombia se da en primer semestre, y los asistentes al seminario son de quinto y sexto semestre, se ve la necesidad de reforzar los temas de estadística inferencial para que los estudiantes vean la posibilidad de soportar sus investigaciones con datos tratados estadísticamente y dado el carácter investigativo de la Facultad.

## Consideraciones

El curso está lleno de contenidos prácticos y ligeros que no exigen a los estudiantes mayores conocimientos o destrezas sobre los temas ni la realización de tareas o trabajos profundos por fuera del aula. Más bien es impartir conocimiento y entregar herramientas básicas de estadística como apoyo a las investigaciones y documentos exigidos como proyectos de investigación.

## Objetivo General

Ofrecer herramientas de estadística inferencial a los asistentes al seminario de Técnicas Especiales de Investigación II, como repaso de la estadística ofrecida en primer semestre, para que se vea la pertinencia y necesidad de incorporar procesamiento y análisis estadístico a los proyectos de investigación.

## Objetivos Específicos

-   Generar los conceptos y conocimientos sobre estimación y pruebas de hipótesis.
-   Adelantar talleres prácticos que hagan evidentes los conceptos presentados.
-   Orientar la aplicación de estos conceptos en los proyectos particulares de cada estudiante.

## Metodología

Curso magistral con talleres prácticos en donde se involucren todos los asistentes mediante el desarrollo de un taller y exposición de resultados.

## Material

[OpenIntro Statistics](https://openintro.org/book/os/)

http://www.bnm.me.gov.ar/giga1/documentos/EL001858.pdf

```         
@book{132224,
    author = {Kelmansky, Diana M. and Kirschenbaum, Juan Manuel},
    title = {Estadística para todos :},
    publisher = {Instituto Nacional de Educación Tecnológica INET,},
    year = {2009.},
    series = {Las ciencias naturales y la matemática},
    address = {Buenos Aires :},
    edition = {1ª ed.},
    url = {http://www.bnm.me.gov.ar/giga1/documentos/EL001858.pdf}
}


```




