# Episteme

El objetivo de la ciencia es el descubrimiento de verdades generales. Los hechos particulares, por supuesto, son fundamentales, pero una simple recopilación de hechos no constituye una ciencia. En ese sentido, los científicos buscan entender los fenómenos, y para hacerlo intentan develar los patrones en los que ocurren los fenómenos y las relaciones sistemáticas entre ellos. Así pues, conocer los hechos no es suficiente, es necesario explicarlos. 

Uno de los métodos de razonamiento empleados hoy en día en estadística y en las ciencias en general es la inferencia, y sus raíces se hallan profundamente en la filosofía clásica y en el desarrollo del método científico moderno. Por ello, para comprender cómo surgió la inferencia estadística y en qué se fundamenta, es necesario entender primero sus bases epistemológicas.

# La deducción en la filosofía griega clásica

## La ignorancia y la mayéutica socráticas

Sócrates fue uno de los primeros filósofos en enfatizar la importancia del cuestionamiento como herramienta para alcanzar la verdad. Su método, la **mayéutica**, consistía en formular preguntas para ayudar a su interlocutor a descubrir conocimientos por sí mismo, partiendo de sus propias creencias y explorando las inconsistencias en sus respuestas.

De esta manera, obligaba a definir el tema sobre el cual versaba la indagación; después profundizaba de distintas maneras en la definición ofrecida, explicitando y subrayando las carencias y las contradicciones que implicaba; exhortaba a intentar una nueva definición y mediante el mismo procedimiento la criticaba y la refutaba; continuaba actuando de este modo hasta llegar al momento en que el interlocutor se declaraba ignorante, que era el punto fundacional de toda su teoría epistemológica, la ignorancia como primer cimiento del conocimiento. Así, a través del diálogo y la introspección, Sócrates buscaba llevar a los demás hacia una mejor comprensión de conceptos abstractos como la justicia, la verdad y el bien.

A pesar de que Sócrates no estableció de manera sistemática los principios fundamentales de la lógica occidental ni desarrolló las nociones de concepto y razonamiento, sus planteamientos ejercieron un impulso notable en esa dirección, desencadenando el proceso que llevaría al descubrimiento de la lógica.

## Platón y la dialéctica

En la filosofía griega clásica, se establecía una marcada distinción jerárquica entre dos grados del conocimiento, a saber, la doxa (opinión) y la episteme (ciencia). Más aún, Platón, distingue una subdivisión en cada uno de estos grados: por un lado, la opinión se divide en la imaginación y en la creencia; por otro lado, la ciencia se divide en conocimiento medio y en la intelección. 

De acuerdo con el pensamiento platónico, el común de la sociedad se detiene meramente en las dos formas del opinar, como los dos grados más bajos del conocimiento, mientras que los matemáticos se elevan hasta el conocimiento medio y el filósofo accede a la intelección y, por tanto, a la ciencia suprema. Esto se debe a que sólo el filósofo conoce el procedimiento, mediante el cual el intelecto avanza o se mueve de idea en idea, que constituye la dialéctica.

Ahora bien, hay una dialéctica ascendente, que es aquella que libera de los sentidos y de lo sensible, lleva hasta las ideas y más tarde, de idea en idea, hasta la Idea suprema. Y hay también una dialéctica descendente que recorre el camino opuesto, es decir, que parte de la Idea suprema o de ideas generales y, distinguiendo paulatinamente aquellas ideas particulares que están contenidas en las generales, llega a determinar cuál es el lugar que una idea en particular ocupa dentro de la estructura jerárquica del mundo ideal. Como es posible intuir, estas dos vías de la dialéctica serán las ideas precursoras de los razonamientos inductivos y deductivos reconocidos y definidos posteriormente por Aristóteles.

## La lógica de Aristóteles

Aristóteles, discípulo a su vez de Platón, sistematizó la lógica clásica como el método racional de todas las ciencias, es decir, como el instrumento que utilizan para pensar y expresar de modo coherente sus conocimientos. En otras palabras, la lógica es el **Organon** común a todas las ciencias, definición que se deriva necesariamente de la obra que la lleva por nombre.

El objeto de estudio de la lógica es la validez del pensamiento, sin embargo, debe quedar en claro a qué nos referimos cuando hablamos de validez. Así pues, podría asegurarse que la validez es la coherencia que existe entre la conclusión y las premisas de un razonamiento, de manera que de ser verdaderas las premisas, necesariamente lo es también la conclusión; y que la verdad de la conclusión sólo depende de si su afirmación coincide con la realidad y no necesariamente con las premisas, por lo que un razonamiento válido no tiene por qué ser un razonamiento verdadero, en la medida en que la verdad va más allá del campo de estudio de la lógica y pasa al campo propio de cada una de las ciencias. 

En definitiva, se requiere que cada ciencia aporte los datos empíricos de buena calidad, léase verdaderos, y la lógica se ocupará de derivar de estas buenas premisas una conclusión igualmente verdadera. De acuerdo con estas ideas, Aristóteles desarrolló una lógica analítica basada en tres grandes teorías: la teoría del concepto, la teoría del juicio y la teoría del razonamiento. En esta última nos detendremos un poco, gracias a que es en ella que se exponen los fundamentos de la argumentación deductiva en la ciencia, principalmente a través del silogismo. 

### El silogismo

Uno de los aportes más significativos de Aristóteles a la epistemología es el **silogismo**, una forma de razonamiento deductivo que permite derivar conclusiones a partir de dos o más premisas. El silogismo establece que, si las premisas son verdaderas y se respetan las reglas lógicas, la conclusión necesariamente debe serlo. Este tipo de razonamiento deductivo es un modelo de inferencia lógica que ha servido de base para la argumentación científica y el desarrollo de sistemas matemáticos y estadísticos durante siglos. 

El ejemplo clásico, empleado por el mismo Aristóteles, está compuesto por las siguientes premisas:

(a) Todos los hombres son mortales.
(b) Sócrates es un hombre.

Y supone, como conclusión, que:

(c) Sócrates es mortal.

Quienes se han dedicado al estudio de la lógica dieron nombre a los tres términos que aparecen en el silogismo. Al que hace de puente lo llamaron término medio, al que hace de predicado en la conclusión, término mayor, y al que hace de sujeto en la misma, término menor. Así, en el ejemplo, el término mayor es mortal, el término menor, Sócrates y el término medio es hombre. Además, establecieron una serie de reglas generales del silogismo que denotan el carácter específico de esta forma categórica de razonamiento deductivo: 

1.	Todo silogismo consta de tres términos.
2.	El término medio no debe aparecer en la conclusión.
3.	El término medio debe estar tomado en toda su extensión por lo menos una vez.
4.	Ningún término puede estar tomado en su extensión en la conclusión si no lo está en la premisa respectiva.
5.	De dos premisas negativas no puede obtenerse válidamente una conclusión.
6.	De dos premisas particulares no puede obtenerse válidamente una conclusión.
7.	Dadas dos premisas afirmativas, la conclusión debe ser afirmativa. 
8.	La conclusión sigue la parte más débil, a saber, lo no universal y lo negativo.

De estas reglas generales del silogismo es posible extraer unas características propias de la deducción, a saber, que en este tipo de razonamiento la conclusión se deriva de las premisas y su conclusión no puede exceder la extensión o cantidad de ninguna de sus premisas. Este aspecto supone una enorme restricción en su uso dentro de la argumentación científica, a menos que se haga referencia a verdades formales, como en el caso de la matemática.

Un ejemplo del uso del método deductivo es el segundo libro más editado de la historia, *Los Elementos* de Euclides, que organiza el conocimiento geométrico mediante un sistema axiomático. En este texto, Euclides parte de unos pocos postulados y axiomas fundamentales, a partir de los cuales deduce rigurosamente una serie de teoremas y proposiciones. 

Otros ejemplos son *Ética demostrada según el orden geométrico* de Spinoza y *Philosophiæ Naturalis Principia Mathematica* de Isaac Newton. En la *Ética*, Spinoza estructura su filosofía siguiendo el estilo geométrico de Euclides, utilizando definiciones, axiomas y proposiciones para desarrollar sus ideas sobre la naturaleza de Dios, la mente y la moralidad. Por su parte, en los *Principia Mathematica*, Newton aplica un razonamiento deductivo para establecer las leyes del movimiento y la gravitación universal, partiendo de principios fundamentales y llegando a conclusiones que explican fenómenos físicos observables. 

# El *Novum Organum* de Bacon

En el siglo XVII, Francis Bacon introdujo un enfoque revolucionario en su obra *Novum Organum*, publicada en 1620 con la intención de sustituir el Organum aristotélico, en la que defendía la **inducción** como el método verdadero del conocimiento científico. Este enfoque rompió con la tradición aristotélica basada en la deducción, proponiendo que, en lugar de solo partir de premisas generales, los científicos deberían observar y analizar los fenómenos específicos para, a partir de ellos, generalizar leyes y principios. El trabajo de Bacon es fundamental porque sentó las bases para una ciencia basada en la observación empírica.

## La deducción contra la inducción

Para Bacon, Aristóteles fue el símbolo de una filosofía estéril debido a que es inútil para la investigación de las ciencias. Además, es perjudicial, porque no sirve más que para consolidar y transmitir los errores de la tradición. Del mismo modo, Bacon se opone al uso del silogismo, en la medida en que éste consta de proposiciones, y las proposiciones se componen de palabras, y éstas, a su vez, representan nociones, en las cuales no hay nada de riguroso. El mismo análisis puede aplicarse a la idea de axioma, debido a que no han sido abstraídos siguiendo un método. En esto consiste precisamente la falsa inducción, a la que Bacon antepone la verdadera inducción.

De acuerdo con sus postulados, sólo existe un camino correcto para buscar y descubrir la verdad: de los sentidos y de lo particular se extraen los axiomas, ascendiendo de manera gradual y sin interrupciones la escala de la generalización, hasta llegar a los axiomas más generales. Estos principios, de útil aplicación, solo pueden ser el resultado de la aplicación de un método, de forma continuada y por grados.

A propósito de esta idea de utilidad, Bacon sostiene que debemos sustituir la cultura retórico-literaria por una cultura técnico-científica, proyecto que lo acompañó durante toda su vida. Esta idea consistía en que el saber debía llevar sus resultados a la práctica, con el fin de transformar y mejorar las condiciones de vida de los seres humanos. Si bien esta es una idea muy aceptada en la actualidad, en su contexto supuso una aplicación de la ciencia para la ampliación del poder del ser humano sobre la naturaleza, como el fruto de una colectividad organizada de científicos.

En suma, el problema del método analizado por Bacon pasa necesariamente por una revaloración del procedimiento inductivo y por un cuestionamiento radical del modelo deductivo propio del silogismo. No obstante, la observación de los casos particulares también debe ser depurada de los prejuicios que constantemente acechan al conocimiento y que Bacon describe minuciosamente en su doctrina de los ídolos. 

### Actividad: ¿Qué es un cisne negro?

El concepto de "cisne negro" se refiere a eventos altamente improbables e impredecibles, pero con un gran impacto cuando ocurren. La expresión fue popularizada por el filósofo Nassim Nicholas Taleb y subraya la limitación de los métodos inductivos, ya que una amplia observación de cisnes blancos no garantiza que no existan cisnes negros. Este concepto es clave para entender los límites de la inferencia estadística y la probabilidad, pues resalta la posibilidad de eventos fuera de nuestras expectativas basadas en observaciones pasadas.

# Fisher, Neyman y Pearson

## Las reglas para hacer inducción

En la estadística moderna, Ronald A. Fisher, Jerzy Neyman y Egon Pearson fueron fundamentales para estructurar las **reglas para hacer inducción**. Su trabajo permitió la formalización de métodos inferenciales que ayudan a generalizar conclusiones a partir de muestras. Estas reglas establecen la estructura de las pruebas de hipótesis y la generación de intervalos de confianza, permitiendo a los científicos tomar decisiones con base en evidencia empírica.

Fisher, Neyman y Pearson desarrollaron metodologías para derivar conocimiento a partir de datos de manera rigurosa, incorporando conceptos como la probabilidad y el error estadístico. A través de la estadística inferencial, lograron definir un proceso sistemático para probar hipótesis, medir la incertidumbre y proporcionar intervalos de confianza, contribuyendo significativamente a las ciencias experimentales y sociales.

## Inferencia estadística

La inferencia estadística surgió en el siglo XX como una disciplina clave en la estadística, impulsada por la necesidad de tomar decisiones informadas a partir de datos. Fisher introdujo conceptos fundamentales como el "p-valor" y la prueba de hipótesis, mientras que Neyman y Pearson formalizaron la teoría de pruebas con su trabajo sobre errores tipo I y II y la formulación de intervalos de confianza. La inferencia estadística se consolidó rápidamente en diversas áreas científicas, desde la biología y la medicina hasta las ciencias sociales y económicas, transformando la manera en que los investigadores validan teorías y estiman parámetros poblacionales. A lo largo del tiempo, esta área ha evolucionado, incorporando herramientas computacionales y métodos bayesianos que amplían las posibilidades de análisis en contextos de datos complejos y grandes volúmenes de información.
