# Medición

## Indicadores y métricas

Los indicadores son herramientas cuantitativas utilizadas para medir, monitorear y evaluar un fenómeno o proceso específico. Un indicador generalmente se compone de un numerador y un denominador, lo que permite contextualizar la medición y compararla en diferentes situaciones. Por ejemplo, un indicador común en economía es la tasa de desempleo, que se calcula dividiendo el número de personas desempleadas (numerador) por la población activa total (denominador), y se expresa como un porcentaje.

Las métricas, aunque también son números que sirven para evaluar aspectos de un fenómeno, suelen referirse a medidas directas que no necesariamente requieren un numerador y un denominador. Son herramientas clave en la evaluación del rendimiento y pueden incluir una amplia gama de datos, desde cifras de ventas hasta tiempos de respuesta en un sistema. Por ejemplo, en un sitio web, una métrica común es el tiempo promedio que un usuario pasa en una página.

## Puedes medir usando un indicador: ¿pero quieres?

### ¿Por qué no puedo ver a mi médico la otra semana?

En gran Bretaña, se propuso medir la calidad de la salud con un indicador: que cuando un paciente llamara a su médico, le dieran cita en menos de cuarenta y ocho horas. Spoiler: [(no funcionó, sólo se atendían llamadas para atención inmediata y se prohibieron las citas por adelantado)](https://www.standard.co.uk/news/mother-catches-out-blair-over-gps-7272924.html).

### Aquí las ambulancias no llegan

En gran Bretaña, se propuso medir la calidad de la salud con un indicador: que cuando había una llamada de emergencia desde una zona urbana, y se consideraba que el caso _ponía en peligro una vida humana de forma inmediata_ el servicio
de ambulancias tenía ocho minutos para llegar al lugar. Spoiler: [no funcionó, las ambulancias sólo iban a lugares cercanos. Cancelaban servicios y reiniciaban rutas.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2667302/pdf/rssa0172-0161.pdf).

## Constructos

### Definición

Un constructo es un aspecto medible relacionado con el fenómeno o sistema que se investiga. Un constructo puede ser unidimensional (linealidad) o multidimensional (complejidad). Generalmente, la medición de un constructo no se puede realizar de manera directa. Este concepto es usado en economía, psicometría, marketing, etc.

Según Gras (1980) un constructo es la representación sobre algún aspecto sobre el objeto que será observado, medido y relacionado con otros constructos. 


## Tipos de constructos

### Constructos formativos

Se miden a partir de sus causas.

 - Calidad.
 - Estrato.
 - Score de crédito.

### Constructos reflexivos

Se miden a partir de sus consecuencias.

 - Logro académico.
 - Riesgo psicosocial.
 - Desempeño laboral.

## Medición de constructos

La medición de un constructo es una variable latente. Las variables latentes requieren una medición indirecta, que se realiza a partir de variables observables.

Briones (1998) establece que los constructos son medibles a través de sus manifestaciones externas, es decir, sus indicadores. Los constructos pueden ser definidos como propiedad subyacentes medidos solamente en forma indirecta, son definiciones mentales de los eventos de objetos los cuales pueden variar.

Los constructos se miden mediante instrumentos. Los instrumentos pasan por un proceso de validación.

## Validación

Validar un instrumento requiere la realización de un proceso de recolección de datos.

### Validez

Que el instrumento concuerde con el constructo que dice medir.

 - Según algunos, la sección de matemáticas en la prueba Saber 11 depende demasiado de la comprensión de lectura.

### Confiabilidad

Al repetir la medición, los resultados se mantienen.

 - Según algunos, los resultados de metemáticas de años distintos de la prueba Saber 11, no son comparables entre sí.

## Validez de contenido

Los ítems agotan el constructo.

Un cuestionario se evalúa solicitando a un grupo de expertos que puntúen los ítems en varios aspectos. Generalmente, los aspectos a evaluar son:

 - Duración: cuánto toma responder el cuestionario.
 - Claridad: que la persona logre comprender las preguntas.
 - Completitud: que las respuestas agoten las posibles opciones a las preguntas.
 - Pertinencia: que las respuestas sean pertinentes.
 
La concordancia entre expertos se mide utilizando un procedimiento, como el Kappa de Cohen o el Kappa de Fleiss.

## Validez convergente y discriminante

Son dos tipos de validez complementarios.

### Convergente

Que los ítems que están relacionados con el constructo en la teoría lo estén en la realidad.

### Discriminante

Que los ítems que no están relacionados con el constructo en la teoría no lo estén en la realidad.

## Consistencia interna

La consistencia interna es la propiedad de los ítems de estár altamente correlacionadas entre sí, lo que indica que están asociadas a un trazo latente. Dado que esta consistencia interna se encuentra reflejada en la estructura de correlación de las variables es posible medirla y analizarla.

### Medidas

Algunas de las medidas más usadas para analizar la consistencia entre variables.

 - [Alfa de Cronbach](https://doi.org/10.1007/BF02310555)
 
 - Lambda de Guttman.

 - Inter Item Correlation (Cohen & Swerdlik, 2005).

## Consistencia externa

La medición que hacemos es consistente con la obtenida mediante otros instrumentos.



## Alpha de Cronbach


### Consistencia interna

En los casos donde todas las variables son mediciones indirectas distintas de un mismo aspecto no medible, se hace referencia a la propiedad denominada consistencia interna. La consistencia interna consiste en la propiedad de las variables en estar altamente correlacionadas entre sí, lo que indica que están asociadas a un trazo latente. Dado que esta consistencia interna se encuentra reflejada en a estructura de correlación de las variables es posible medirla y analizarla. 


## Alpha de Cronbach

El Alfa de Cronbach [@Cronbach1951] es una de las medidas más usadas para analizar la consistencia entre variables.

Dados $K$ variables $Y_1, Y_2, ..., Y_K$ y su suma $X = Y_1 + Y_2 + ... + Y_K$, el Alfa de Chronbach está dado por la expresión

$$\alpha = \frac{K}{K-1} \left(1-\frac{\sum_{i = 1}^K \sigma^2_{Y_i}}{\sigma^2_X}\right)$$

## Alfa de Cronbach

> El valor mínimo aceptable para el coeficiente alfa de Cronbach es 0,70; por debajo de ese valor la consistencia interna de la escala utilizada es baja. Por su parte, el valor máximo esperado es 0,90; por encima de este valor se considera que hay redundancia o duplicación.

[Aproximación al uso del coeficiente alfa
de Cronbach](http://scielo.org.co/pdf/rcp/v34n4/v34n4a09.pdf)




## Instrumentos

Un instrumento de medida es una técnica o conjunto de técnicas que permitirán una asignación numérica que cuantifique las manifestaciones de un constructo que  es  medible  solo  de  manera  indirecta. (Herrera, 1998)

## Cuestionarios

Un cuestionario es un conjunto de preguntas que indagan por aspectos concernientes al constructo. 

Las preguntas o ítems tienen un valor particular en la construcción de un cuestionario.

## Construcción

La construcción de un cuestionario, es decir, de definición de las preguntas que lleva, no ocurre de manera subjetiva.

Es preferible tomar como base cuestionarios previos o estudios detallados anteriores o partir de una investigación cualitativa anterior.

## La pregunta

 - Qué se pregunta. Debe estar relacionado con lo que se quiere medir.
 - Cada pregunta es atómica. No indaga por diferentes aspectos al mismo tiempo.

## Tipos de preguntas

Las preguntas que se realizan pueden ser:

### Abiertas

 - El usuario responde un párrafo con sus apreciaciones.
 - En general no se incluyen por no tener un abordaje desde la estadística clásica.
 - Pueden ser analizadas con minería de texto y procesamiento del lenguaje natural.

### Cerradas

 + Numéricas
 + Opción múltiple con única respuesta.
 + Opción múltiple con múltiple respuesta (el análisis no es tan fácil).

## Estructuras de preguntas

Algunos mecanismos de indagación más compleja.

 + Votos múltiples.
 + Ranking.
 + Likert.

## Votos múltiples

Es una estructura de votación, cada integrante del grupo tiene un número de votos con respecto a un conjunto de alternativas. A diferencia de una votación única, donde se selecciona solo una opción, la votación múltiple permite elegir varias opciones, ofreciendo una visión más completa de las preferencias del grupo.

Ejemplo: Imagina que tienes una lista de marcas de automóviles: Tesla, BMW, Mercedes, Audi, Toyota, Ford, Honda, Volvo. Se te pide que votes por las tres marcas que más te gusten. 

¿Cómo crees que se analiza?

## Ranking

Se solicita a los participantes que organicen de mayor a menor una lista según un criterio definido. Este proceso permite capturar las preferencias relativas entre las diferentes opciones.

Ejemplo: Imagina que tienes una lista de postres: tiramisú, helado de vainilla, cheesecake, brownie, mousse de chocolate, flan, macarrones, crème brûlée. Se te pide que los organices de mayor a menor según lo deliciosos que te parezcan.

¿Cómo crees que se analiza?

## Likert

Se solicita a los participantes que puntúen una lista de afirmaciones según una escala definida.

Ejemplo: Imagina que se les pide a los participantes que expresen su nivel de acuerdo con las siguientes afirmaciones sobre ética en el lugar de trabajo:

"Es aceptable que los empleados reporten irregularidades de manera anónima."

"Las empresas deben ser transparentes sobre sus prácticas ambientales."

"Es importante que las decisiones corporativas se basen en principios éticos, incluso si afecta la rentabilidad."

Los participantes deben calificar cada afirmación en una escala que va desde "totalmente en desacuerdo", "en desacuerdo", "neutral", "de acuerdo" hasta "totalmente de acuerdo".

¿Cómo crees que se analiza?

## Buenas prácticas

En los procesos de diseño de instrumentos hay una serie de buenas prácticas:

 - No usar filtros en las encuestas.
 - Nunca ponerle número a las categorías ni a la no respuesta.
 - No hacer preguntas tendenciosas.
 - Usar palabras claras.
 - No dar alternativas implícitas.
 - No hacer suposiciones tácitas.
 - No usar dobles negaciones.
 - Mejor preguntar la fecha de nacimiento que la edad.
 - Preguntar como numéricos los datos numéricos siempre que sea posible.


# Referencias

Cohen, R. J., Swerdlik, M. E., & Phillips, S. M. (1996). Psychological testing and assessment: An introduction to tests and measurement. Mayfield Publishing Co.

