# ToDo  {.unnumbered}


```{r}
# justificar los textos vía css
# Pruebas de hipótesis: analíticas paramétricas, analíticas no paramétricas, computacionales paramétricas, computacionales no paramétricas.
# Poner todas las fórmulas en cajas
# Variables cualitativas, cómo se ven en un gráfico, cuáles son sus elementos visuales, cómo se trabajan en modelamiento, datos cíclicos, datos textuales
# Hacer capítulo de preparación de los datos.
#### Completar la fórmula de las estadíustias descriptivas
# Actualizar los covers para que coincidan con los capítulos
# Organizar modelamiento supervisado
# Organizar modelamiento no supervisado
# Que todo salga en pdf
# Poner una portada
```


Asignación de capítulos:

```{r}
# C01_prelim: Juan Diego.
# C01_prepara: Néstor
# C01_corr: Miguel
# C01_vis: Néstor
# C01_dist: Miguel
# C02_episteme: Juan Diego
# 
# Asignación de tareas
# 
# Portada: Néstor
# Revisión global: Todos
# Revisón bibliográfica: Raquel
# Diagramas: Raquel
# Revisión de publicación (tablas y gráficos): Raquel
# Prólogo: ?
# 
# 
# 
# Importante: Citación y bibliografía en cada capítulo en bibtex
# 
# 

```


::: {.callout-tip}
## Ejemplo

Caja para escribir ejemplos

:::


::: {.callout-warning}
## Fórmula

Caja para escribir fórmulas

:::



